### ISSUE TITLE
Segfault with openblas 0.3.10

### ISSUE THREAD

**Issue by ogrisel** [conda-forge/openblas-feedstock#104]
I have observed a regression with openblas 0.3.10:

```python
import numpy as np

np.ones(shape=(300000, 5)) @ np.ones(shape=(5, 5))
```

=> segfaults.

No problem with 0.3.9.

I will report upstream but maybe we might want to mark 0.3.10 as a bad release in conda-forge? Are we might do that once a bugfix release is available from upstream?

Original bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/issues/17980

**Comment by h-vetinari** [comment]
Hello @ogrisel, what platform / OS are you on?

This issue is very likely a duplicate of #101; we have already backported the upstream [fix](https://github.com/xianyi/OpenBLAS/pull/2729) that's (in all likelihood) the underlying [issue](https://github.com/xianyi/OpenBLAS/issues/2728) for this since [yesterday](https://github.com/conda-forge/openblas-feedstock/pull/103), so could you please try updating to the latest build (`openblas-0.3.10-<...>_4`) and checking if the issue persists?

**Comment by ogrisel** [comment]
Sorry: Linux 64bit.

**Comment by ogrisel** [comment]
I confirm your fix works. That was quick!

Thanks.
