### ISSUE TITLE
Provide libblas.so and liblapack.so

### ISSUE THREAD

**Issue by isuruf** [conda-forge/openblas-feedstock#23]
Any reason why https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/build.sh#L46-L49 is commented?

**Comment by jschueller** [comment]
maybe it conflicts with lapack-feedstock ?

**Comment by isuruf** [comment]
Thanks. Shouldn't that be handled by features, just like blas is? I mean have lapack package track a lapack feature and let netlib and openblas be two providers.

**Comment by jschueller** [comment]
yes it should

**Comment by jakirkham** [comment]
FYI OpenBLAS has its own LAPACK.

As far as those lines, I commented them from the outset as there was a thought that people might be able to mix BLAS implementations. However, we have since seen this cause crashes (e.g. mixing linked libraries with OpenBLAS and MKL). So it might be ok to uncomment them. For the most part, if I need those lines, I add them to the recipe that builds with a BLAS and then remove the symlinks at the end of the build.

**Comment by isuruf** [comment]
It's weird that conda-forge has only one blas implementation (openblas and no netlib) but has two lapack (openblas and netlib) with the netlib lapack bundling netlib's blas.

**Comment by isuruf** [comment]
Created https://github.com/conda-forge/blas-feedstock/issues/6
